Merge custom config with default
kubedb/kafka-docker pull request #10
Opened 2023-06-06 08:36 UTC by obaydullahmhs

Signed-off-by: obaydullahmhs <obaydullah@appscode.com>

2023-06-06 08:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/kafka-docker?pullRequest=10) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/kafka-docker?pullRequest=10) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: tamalsaha<br/>:white_check_mark: raihankhan<br/>:x: obaydullahmhs<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/kafka-docker?pullRequest=10) it.</sub>

2023-06-14 10:47 UTC, raihankhan requested changes

2023-06-14 10:47 UTC, raihankhan commented on entrypoint.sh
> +  fi
Add comment > why we should delete cluster quorum state

2023-06-14 10:47 UTC, raihankhan commented on entrypoint.sh
> +    OUTPUT_FILE="/opt/kafka/config/kafkaconfig/config.properties.merged"
Convert all env var to small case

2023-06-14 10:47 UTC, raihankhan commented on entrypoint.sh
> +      echo "No custom configuration found"
Remove this log

2023-06-14 10:47 UTC, raihankhan commented on entrypoint.sh
> +    arr=("process.roles", "cluster.id", "node.id", "controller.quorum.voters",
Try the Array without commas

2023-06-14 10:47 UTC, raihankhan commented on entrypoint.sh
> +    # Delete the output file if exists
Mention previous

2023-06-14 10:47 UTC, raihankhan commented on entrypoint.sh
> +    fi
Remove this part if unnecessary

2023-06-14 10:47 UTC, raihankhan commented on Dockerfile
Add ref link for kafkacat

2023-07-17 06:42 UTC, raihankhan approved these changes
LGTM!

2023-07-17 07:04 UTC, heheh13 approved these changes

2023-07-17 07:09 UTC, merged